#!/usr/bin/env python3
"""
generate-catalog.py — Generates CATALOG.md and skills_index.json from SKILL.md frontmatter.

Reads all skills under skills/ directory, parses frontmatter, and produces:
1. CATALOG.md — markdown table grouped by category
2. skills_index.json — JSON array of all skills with metadata

Usage:
    python tools/generate-catalog.py
"""

import os
import re
import json
from datetime import datetime, timezone


def parse_frontmatter(filepath):
    """Extract YAML frontmatter from a SKILL.md file."""
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()

    match = re.match(r"^---\s*\n(.*?)\n---\s*\n", content, re.DOTALL)
    if not match:
        return None

    frontmatter_text = match.group(1)
    frontmatter = {}

    for line in frontmatter_text.strip().split("\n"):
        line = line.strip()
        if not line or line.startswith("#"):
            continue

        colon_idx = line.find(":")
        if colon_idx == -1:
            continue

        key = line[:colon_idx].strip()
        value = line[colon_idx + 1:].strip()

        if value.startswith("[") and value.endswith("]"):
            items = value[1:-1].split(",")
            frontmatter[key] = [item.strip().strip("'\"") for item in items if item.strip()]
        elif value.startswith('"') and value.endswith('"'):
            frontmatter[key] = value[1:-1]
        elif value.startswith("'") and value.endswith("'"):
            frontmatter[key] = value[1:-1]
        else:
            frontmatter[key] = value

    return frontmatter


def generate_catalog_md(skills_by_category):
    """Generate CATALOG.md content."""
    lines = [
        "# Marlin Skill Catalog",
        "",
        "> Auto-generated from SKILL.md frontmatter. Do not edit manually.",
        f"> Last generated: {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}",
        "",
    ]

    category_order = [
        "compression", "parsing", "schema", "encoding",
        "formatting", "estimation", "bridge"
    ]

    for category in category_order:
        if category not in skills_by_category:
            continue

        skills = skills_by_category[category]
        lines.append(f"## {category.title()}")
        lines.append("")
        lines.append("| Name | Phase | Trigger | Token Impact | Stability |")
        lines.append("|------|-------|---------|-------------|-----------|")

        for skill in sorted(skills, key=lambda s: s.get("name", "")):
            name = skill.get("name", "unknown")
            phase = skill.get("phase", "—")
            trigger = skill.get("trigger", "—")
            token_impact = skill.get("token_impact", "—")
            stability = skill.get("stability", "—")
            trigger_display = f"`{trigger}`" if trigger != "internal" else "_internal_"
            lines.append(
                f"| [{name}](skills/{name}/SKILL.md) | {phase} | {trigger_display} | {token_impact} | {stability} |"
            )

        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(
        "Generated by `tools/generate-catalog.py` — do not edit manually. "
        "Run `python tools/generate-catalog.py` to regenerate."
    )
    lines.append("")

    return "\n".join(lines)


def generate_skills_index(all_skills):
    """Generate skills_index.json content."""
    index = {
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "total": len(all_skills),
        "skills": sorted(all_skills, key=lambda s: s.get("name", "")),
    }
    return json.dumps(index, indent=2, ensure_ascii=False)


def main():
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    skills_root = os.path.join(repo_root, "skills")

    if not os.path.isdir(skills_root):
        print("ERROR: skills/ directory not found")
        return

    all_skills = []
    skills_by_category = {}

    skill_dirs = sorted([
        d for d in os.listdir(skills_root)
        if os.path.isdir(os.path.join(skills_root, d)) and not d.startswith(".")
    ])

    for skill_name in skill_dirs:
        skill_path = os.path.join(skills_root, skill_name, "SKILL.md")
        if not os.path.isfile(skill_path):
            print(f"  SKIP: {skill_name} (no SKILL.md)")
            continue

        frontmatter = parse_frontmatter(skill_path)
        if not frontmatter:
            print(f"  SKIP: {skill_name} (invalid frontmatter)")
            continue

        # Add path to frontmatter
        frontmatter["path"] = f"skills/{skill_name}/SKILL.md"

        all_skills.append(frontmatter)

        category = frontmatter.get("category", "uncategorized")
        if category not in skills_by_category:
            skills_by_category[category] = []
        skills_by_category[category].append(frontmatter)

    # Write CATALOG.md
    catalog_path = os.path.join(repo_root, "CATALOG.md")
    catalog_content = generate_catalog_md(skills_by_category)
    with open(catalog_path, "w", encoding="utf-8") as f:
        f.write(catalog_content)
    print(f"  [OK] Generated CATALOG.md ({len(all_skills)} skills)")

    # Write skills_index.json
    index_path = os.path.join(repo_root, "skills_index.json")
    index_content = generate_skills_index(all_skills)
    with open(index_path, "w", encoding="utf-8") as f:
        f.write(index_content)
    print(f"  [OK] Generated skills_index.json ({len(all_skills)} skills)")


if __name__ == "__main__":
    main()
